typography_spectrum: 0.6324871738894963
color:
  brandStrength: 0.6255088459463366
  lightness: 0.9726048168097392
  saturation: 0.4743721087438303
  rhythmicContrast: 0.8014844084628812
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
layout_spectrum: 0.052350698863755506
analytics:
  google: UA-86416819-1
author:
  name: Jonathan Dempsey
  email: jonathan.a.dempsey@gmail.com
  url: about-me-jd
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/85d07d8f-a607-4d49-b330-90fabeb3dc23.jpg
name: Student Affairs UK
navigation:
  - name: Home
    url: 'http://studentaffairs.co.uk/'
    type: external
  - name: 'Hello, world'
    id: 329d99f3-da1f-4752-b0cf-49d77d197f42
    type: content
  - name: 'About me, JD'
    id: dbab1904-ffac-446b-bf7b-dac1fc591bb7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ad53765d-f174-4b95-86dd-ad47759e2d12.jpg
title: Student Affairs UK
content: []
coverPrefs:
  filter: false
description: My corner of the internet to talk all things student affairs
purpose:
  - type: external
    url: 'https://goo.gl/AXGerg'
    label: Tweet me
  - type: email
    label: Contact me
    url: 'mailto:jonathan.a.dempsey@gmail.com'
