layout_spectrum: 0.2594812484504194
typography_spectrum: 0.632670112003729
color:
  brandStrength: 0.6296030971196729
  lightness: 0.9767292191019041
  saturation: 0.47912308723130953
  rhythmicContrast: 0.8022551973539377
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
coverPrefs:
  filter: false
github: true
analytics:
  google: UA-86416819-1
author:
  name: Jonathan Dempsey
  email: jonathan.a.dempsey@gmail.com
  url: about-me-jd
logo: null
name: Student Affairs UK
navigation:
  - name: Home
    url: 'http://studentaffairs.co.uk/'
    type: external
  - name: 'Hello, world'
    id: 329d99f3-da1f-4752-b0cf-49d77d197f42
    type: content
  - name: 'About me, JD'
    id: dbab1904-ffac-446b-bf7b-dac1fc591bb7
    type: content
favicon: null
title: Student Affairs UK
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6f8fc3e-c4bc-4ec0-ba0e-e65d9f9b876a.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d6f8fc3e-c4bc-4ec0-ba0e-e65d9f9b876a.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1fb0c3da-a42e-42a5-a390-b20707f11995.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1fb0c3da-a42e-42a5-a390-b20707f11995.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: My corner of the internet to talk all things student affairs
purpose:
  - type: external
    url: 'https://goo.gl/AXGerg'
    label: Tweet me
  - type: email
    label: Contact me
    url: 'mailto:jonathan.a.dempsey@gmail.com'
