typography_spectrum: 0.6030413037488734
color:
  brandStrength: 0.49040078127876585
  lightness: 0.443313958972213
  saturation: 0.5958501413493131
  rhythmicContrast: 0.3523066399153322
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
layout_spectrum: 0.3879266471779066
analytics:
  google: UA-86416819-1
author:
  name: Jonathan Dempsey
  email: jonathan.a.dempsey@gmail.com
name: Student Affairs UK
navigation:
  - name: Home
    url: 'http://studentaffairs.co.uk/'
    type: external
  - name: 'About me, JD'
    id: dbab1904-ffac-446b-bf7b-dac1fc591bb7
    type: content
title: Student Affairs UK
content: []
description: My corner of the internet to talk all things student affairs
purpose:
  - type: external
    url: twitter.com/intent/tweet?text=%40JD_in_HE
    label: Tweet me!
  - type: email
    label: Contact me
    url: 'mailto:jonathan.a.dempsey@gmail.com'
