layout_spectrum: 0.2594812484504194
typography_spectrum: 0.632670112003729
color:
  brandStrength: 0.6296030971196729
  lightness: 0.9767292191019041
  saturation: 0.47912308723130953
  rhythmicContrast: 0.8022551973539377
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
coverPrefs:
  filter: false
github: true
analytics:
  google: UA-86416819-1
author:
  name: Jonathan Dempsey
  email: jonathan.a.dempsey@gmail.com
  url: about-me-jd
logo: null
name: Student Affairs UK
navigation:
  - name: Home
    url: 'http://studentaffairs.co.uk/'
    type: external
  - name: 'Hello, world'
    id: 329d99f3-da1f-4752-b0cf-49d77d197f42
    type: content
  - name: 'About me, JD'
    id: dbab1904-ffac-446b-bf7b-dac1fc591bb7
    type: content
favicon: null
title: Student Affairs UK
content: []
description: My corner of the internet to talk all things student affairs
purpose:
  - type: external
    url: 'https://goo.gl/AXGerg'
    label: Tweet me
  - type: email
    label: Contact me
    url: 'mailto:jonathan.a.dempsey@gmail.com'
