typography_spectrum: 0.8046369203366339
color:
  brandStrength: 0.4933141751680523
  lightness: 0.44545618165284395
  saturation: 0.5961370281875134
  rhythmicContrast: 0.3531348293181509
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
layout_spectrum: 0.2840648021083325
author:
  name: Jonathan Dempsey
  email: jonathan.a.dempsey@gmail.com
name: Student Affairs UK
navigation:
  - name: 'About me, JD'
    id: dbab1904-ffac-446b-bf7b-dac1fc591bb7
    type: content
  - name: Home
    url: 'http://studentaffairs.co.uk/'
    type: external
title: Student Affairs UK
content: []
description: ''
