name: Student Affairs UK
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/79153781-311d-4517-bbf0-633bdaff3c7b.png
layout_spectrum: 0.2594812484504194
typography_spectrum: 0.632670112003729
analytics:
  google: UA-86416819-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6296030971196729
  lightness: 0.9767292191019041
  saturation: 0.47912308723130953
  rhythmicContrast: 0.8022551973539377
purpose:
  - type: external
    label: Tweet me
    url: 'https://goo.gl/AXGerg'
title: Student Affairs UK
description: My thought on all things HE in the UK
author:
  name: Jonathan Dempsey
  email: jonathan.a.dempsey@gmail.com
content_rating:
  adult: false
navigation:
  - name: Home
    url: 'http://studentaffairs.co.uk/'
    type: external
  - name: 'Hello, world'
    id: 329d99f3-da1f-4752-b0cf-49d77d197f42
    type: content
  - name: 'About me, JD'
    id: dbab1904-ffac-446b-bf7b-dac1fc591bb7
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b3d9424-5f34-46fd-9f13-0fcaf4382499.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b3d9424-5f34-46fd-9f13-0fcaf4382499.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
